services:
  app:
    build:
      context: ./
      target: production
    environment:
      SCHOOLPASS_USERNAME:
      SCHOOLPASS_PASSWORD:
      UNIFI_ACCESS_SERVER: https://server:12445
      UNIFI_ACCESS_API_TOKEN:
    volumes:
      - ./logs:/usr/src/app/logs